# Generated by Django 4.1.5 on 2023-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
