# Generated by Django 4.1.5 on 2023-02-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_posts_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
